const questions = {
  noon_sakinah: [
    {
      id: "ns1",
      word: "مِنْ بَعْدِ",
      transliteration: "min ba'di",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Iqlaab",
      explanation: "Noon sakinah followed by ب applies Iqlaab - the noon is changed to a meem",
    },
    {
      id: "ns2",
      word: "مِنْ قَبْلُ",
      transliteration: "min qablu",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ق requires Ikhfaa",
    },
    {
      id: "ns3",
      word: "مَنْ آمَنَ",
      transliteration: "man aamana",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by a throat letter (ء) requires Ithaar",
    },
    {
      id: "ns4",
      word: "أَنْتُمْ",
      transliteration: "antum",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ت requires Ikhfaa",
    },
    {
      id: "ns5",
      word: "مِنْ عِلْمٍ",
      transliteration: "min 'ilmin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ع requires Ithaar",
    },
    {
      id: "ns6",
      word: "مِنْ يَعْمَلُ",
      transliteration: "min ya'malu",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by ي requires Idghaam with ghunnah",
    },
    {
      id: "ns7",
      word: "عَنْكَ",
      transliteration: "'anka",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ك requires Ikhfaa",
    },
    {
      id: "ns8",
      word: "مِنْ نِعْمَةٍ",
      transliteration: "min ni'matin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by ن requires Idghaam without ghunnah",
    },
    {
      id: "ns9",
      word: "مَنْ حَوْلَكَ",
      transliteration: "man hawlaka",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ح requires Ithaar",
    },
    {
      id: "ns10",
      word: "مِنْ وَلِيٍّ",
      transliteration: "min waliyyin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by و requires Idghaam with ghunnah",
    },
    {
      id: "ns11",
      word: "مِنْ دُونِ",
      transliteration: "min dooni",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by د requires Ikhfaa",
    },
    {
      id: "ns12",
      word: "مِنْ غِلٍّ",
      transliteration: "min ghillin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by غ requires Ithaar",
    },
    {
      id: "ns13",
      word: "مِنْ خَيْرٍ",
      transliteration: "min khayrin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by خ requires Ithaar",
    },
    {
      id: "ns14",
      word: "مَنْ هَادَ",
      transliteration: "man haada",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ه requires Ithaar",
    },
    {
      id: "ns15",
      word: "مِنْ مَاءٍ",
      transliteration: "min maa'in",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by م requires Idghaam with ghunnah",
    },
    {
      id: "ns16",
      word: "أَنْفُسَكُمْ",
      transliteration: "anfusakum",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ف requires Ikhfaa",
    },
    {
      id: "ns17",
      word: "مِنْ لَدُنْهُ",
      transliteration: "min ladunhu",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by ل requires Idghaam without ghunnah",
    },
    {
      id: "ns18",
      word: "مِنْ جَنَّةٍ",
      transliteration: "min jannatin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ج requires Ikhfaa",
    },
    {
      id: "ns19",
      word: "مِنْ زَكَاةٍ",
      transliteration: "min zakaatin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ز requires Ikhfaa",
    },
    {
      id: "ns20",
      word: "مِنْ غَيْرِ",
      transliteration: "min ghayri",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by غ requires Ithaar",
    },
    {
      id: "ns21",
      word: "إِنْ كُنْتُمْ",
      transliteration: "in kuntum",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ك requires Ikhfaa",
    },
    {
      id: "ns22",
      word: "مِنْ أَهْلِ",
      transliteration: "min ahli",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ء requires Ithaar",
    },
    {
      id: "ns23",
      word: "مِنْ شَيْءٍ",
      transliteration: "min shay'in",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ش requires Ikhfaa",
    },
    {
      id: "ns24",
      word: "مِنْ طِينٍ",
      transliteration: "min teenin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ط requires Ikhfaa",
    },
    {
      id: "ns25",
      word: "مِنْ رَبِّهِمْ",
      transliteration: "min rabbihim",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Idghaam",
      explanation: "Noon sakinah followed by ر requires Idghaam without ghunnah",
    },
    {
      id: "ns26",
      word: "مِنْ حَكِيمٍ",
      transliteration: "min hakeemin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ح requires Ithaar",
    },
    {
      id: "ns27",
      word: "أَنْبِئْهُمْ",
      transliteration: "ambi'hum",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Iqlaab",
      explanation: "Noon sakinah followed by ب applies Iqlaab",
    },
    {
      id: "ns28",
      word: "مِنْ صِيَامٍ",
      transliteration: "min siyaamin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ص requires Ikhfaa",
    },
    {
      id: "ns29",
      word: "مِنْ ثَمَرَةٍ",
      transliteration: "min thamaratin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ikhfaa",
      explanation: "Noon sakinah followed by ث requires Ikhfaa",
    },
    {
      id: "ns30",
      word: "مِنْ عَذَابٍ",
      transliteration: "min 'adhabin",
      question: "What rule applies to the noon sakinah?",
      options: ["Ithaar", "Idghaam", "Iqlaab", "Ikhfaa"],
      answer: "Ithaar",
      explanation: "Noon sakinah followed by ع requires Ithaar",
    },
  ],

  qalqalah: [
    {
      id: "ql1",
      word: "يَجْعَلُ",
      transliteration: "yaj'alu",
      question: "What type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ج has a sukoon in the middle of the word - Qalqalah Sughra (light) (minor)",
    },
    {
      id: "ql2",
      word: "يَبْسُطُ",
      transliteration: "yabsutu",
      question: "What type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ب has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql3",
      word: "يَقْطَعُ",
      transliteration: "yaqta'u",
      question: "What type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ق has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql4",
      word: "أَحَدٌ",
      transliteration: "ahad (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the د?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, د gets a sukoon at the end of the word with no shaddah - Qalqalah Wusta (moderate) (middle)",
    },
    {
      id: "ql5",
      word: "الْفَلَقِ",
      transliteration: "al-falaq (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, ق gets a sukoon at end of word with no shaddah - Qalqalah Wusta (moderate)",
    },
    {
      id: "ql6",
      word: "الْحَقُّ",
      transliteration: "al-haqq (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ق has a shaddah at the end of the word - Qalqalah Kubra (heavy) (major), the strongest bounce",
    },
    {
      id: "ql7",
      word: "الْحَجُّ",
      transliteration: "al-hajj (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ج has a shaddah at the end of the word - Qalqalah Kubra (heavy)",
    },
    {
      id: "ql8",
      word: "يَدْخُلُونَ",
      transliteration: "yadkhuloona",
      question: "What type of Qalqalah is on the د?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "د is a qalqalah letter with a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql9",
      word: "قَدْ أَفْلَحَ",
      transliteration: "qad aflaha",
      question: "What type of Qalqalah is on the د?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "د has a sukoon in the middle of the phrase - Qalqalah Sughra (light)",
    },
    {
      id: "ql10",
      word: "الْحَبَّ",
      transliteration: "al-habb (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ب has a shaddah at the end of the word - Qalqalah Kubra (heavy)",
    },
    {
      id: "ql11",
      word: "يَقْبَلُ",
      transliteration: "yaqbalu",
      question: "What type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ق has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql12",
      word: "يَطْبَعُ",
      transliteration: "yatba'u",
      question: "What type of Qalqalah is on the ط?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ط has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql13",
      word: "الْبَقَرِ",
      transliteration: "al-baqar (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "No Qalqalah",
      explanation: "ق here has a fatha (حركة), not a sukoon, so there is no Qalqalah on it when continuing. When stopping, the word ends on ر which is not a qalqalah letter",
    },
    {
      id: "ql14",
      word: "الْحَقِّ",
      transliteration: "al-haqqi (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ق has a shaddah at the end - Qalqalah Kubra (heavy)",
    },
    {
      id: "ql15",
      word: "الْفَجْرِ",
      transliteration: "al-fajr (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "When stopping the word ends on ر, which is not a qalqalah letter. However, ج has a sukoon mid-word when continuing, giving Sughra",
    },
    {
      id: "ql16",
      word: "أَبْتَرُ",
      transliteration: "abtar (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "When stopping the word ends on ر, not a qalqalah letter. ب has a sukoon mid-word when continuing giving Sughra",
    },
    {
      id: "ql17",
      word: "وَالطَّارِقِ",
      transliteration: "wat-taariq (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, ق is at the end of the word with no shaddah - Qalqalah Wusta (moderate)",
    },
    {
      id: "ql18",
      word: "الْمَشْرِقِ",
      transliteration: "al-mashriq (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, ق is at the end with no shaddah - Qalqalah Wusta (moderate)",
    },
    {
      id: "ql19",
      word: "الْحَبِّ",
      transliteration: "al-habb (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ب has a shaddah at the end - Qalqalah Kubra (heavy)",
    },
    {
      id: "ql20",
      word: "يَجْتَبِي",
      transliteration: "yajtabee",
      question: "What type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ج has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql21",
      word: "أَجْدَرُ",
      transliteration: "ajdaru",
      question: "What type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ج has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql22",
      word: "الْإِنجِيلَ",
      transliteration: "al-injeel",
      question: "What type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "No Qalqalah",
      explanation: "ج here has a kasrah (حركة), not a sukoon, so there is no Qalqalah",
    },
    {
      id: "ql23",
      word: "وَالْفَجْرِ",
      transliteration: "wal-fajr",
      question: "What type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ج has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql24",
      word: "الْقَدْرِ",
      transliteration: "al-qadr (when stopping)",
      question: "When stopping, is there Qalqalah on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "No Qalqalah",
      explanation: "ق has a fatha here, not a sukoon. The word ends on ر when stopping, which is not a qalqalah letter",
    },
    {
      id: "ql25",
      word: "الْبُرُوجِ",
      transliteration: "al-burooj (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, ج is at the end of the word with no shaddah - Qalqalah Wusta (moderate)",
    },
    {
      id: "ql26",
      word: "الْحَجِّ",
      transliteration: "al-hajj (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ج?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ج has a shaddah at the end - Qalqalah Kubra (heavy)",
    },
    {
      id: "ql27",
      word: "يَبْتَغِ",
      transliteration: "yabtaghi",
      question: "What type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Sughra (light)",
      explanation: "ب has a sukoon in the middle of the word - Qalqalah Sughra (light)",
    },
    {
      id: "ql28",
      word: "تَبَّتْ",
      transliteration: "tabbat (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ب?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "No Qalqalah",
      explanation: "When stopping the word ends on ت, which is not a qalqalah letter. ب has a fatha on it, so no qalqalah is applied there.",
    },
    {
      id: "ql29",
      word: "الْغَسَقِ",
      transliteration: "al-ghasaq (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Wusta (moderate)",
      explanation: "When stopping, ق is at the end of the word with no shaddah - Qalqalah Wusta (moderate)",
    },
    {
      id: "ql30",
      word: "الْحَقَّ",
      transliteration: "al-haqqa (when stopping)",
      question: "When stopping on this word, what type of Qalqalah is on the ق?",
      options: ["Qalqalah Sughra (light)", "Qalqalah Wusta (moderate)", "Qalqalah Kubra (heavy)", "No Qalqalah"],
      answer: "Qalqalah Kubra (heavy)",
      explanation: "When stopping, ق has a shaddah at the end - Qalqalah Kubra (heavy)",
    },
  ],

  waqf: [
    {
      id: "wq1",
      word: "م",
      transliteration: "Meem (Waqf sign)",
      question: "What does the waqf sign م indicate?",
      options: ["Compulsory stop", "Compulsory join", "Preferred stop", "Permissible stop"],
      answer: "Compulsory stop",
      explanation: "م (Waqf Laazim) - you must stop here. Continuing would change the meaning",
    },
    {
      id: "wq2",
      word: "لا",
      transliteration: "Laa (Waqf sign)",
      question: "What does the waqf sign لا indicate?",
      options: ["Do not stop", "Must stop", "Preferred stop", "Either is fine"],
      answer: "Do not stop",
      explanation: "لا (Waqf Mamnoo) - do not stop here. Stopping would change or break the meaning",
    },
    {
      id: "wq3",
      word: "ج",
      transliteration: "Jeem (Waqf sign)",
      question: "What does the waqf sign ج indicate?",
      options: ["Permissible stop", "Compulsory stop", "Do not stop", "Continuing preferred"],
      answer: "Permissible stop",
      explanation: "ج (Waqf Jaa'iz) - stopping or continuing are both acceptable",
    },
    {
      id: "wq4",
      word: "ط",
      transliteration: "Taa (Waqf sign)",
      question: "What does the waqf sign ط indicate?",
      options: ["Stopping preferred", "Do not stop", "Compulsory stop", "Slight pause only"],
      answer: "Stopping preferred",
      explanation: "ط (Waqf Mutlaq) - stopping here is preferred",
    },
    {
      id: "wq5",
      word: "ص",
      transliteration: "Saad (Waqf sign)",
      question: "What does the waqf sign ص indicate?",
      options: ["Permissible to stop briefly", "Compulsory stop", "Must continue", "Stopping preferred"],
      answer: "Permissible to stop briefly",
      explanation: "ص (Waqf Murakhkhas) - you may stop briefly if out of breath, but better to continue",
    },
    {
      id: "wq6",
      word: "قلي",
      transliteration: "Qaaf Laam Ya (Waqf sign)",
      question: "What does the waqf sign قلي indicate?",
      options: ["Stopping is preferred", "Continuing is preferred", "Compulsory stop", "Do not stop"],
      answer: "Stopping is preferred",
      explanation: "قلي (al-waqf al-awla) - stopping here is slightly preferred over continuing",
    },
    {
      id: "wq7",
      word: "صلي",
      transliteration: "Saad Laam Ya (Waqf sign)",
      question: "What does the waqf sign صلي indicate?",
      options: ["Continuing is preferred", "Stopping is preferred", "Compulsory stop", "Do not stop"],
      answer: "Continuing is preferred",
      explanation: "صلي (al-wasl al-awla) - continuing without stopping is preferred here",
    },
    {
      id: "wq8",
      word: "∴",
      transliteration: "Three dots (Mo'aanaqah)",
      question: "When you see three dots in two places in an ayah, what does it mean?",
      options: ["Stop at one but not both", "Stop at both", "Continue past both", "Stop at the first only"],
      answer: "Stop at one but not both",
      explanation: "Mo'aanaqah - the meaning connects both ways; stop at one set of dots but not both",
    },
    {
      id: "wq9",
      word: "زـ",
      transliteration: "Zaay (Waqf sign)",
      question: "What does the waqf sign ز indicate?",
      options: ["Continuing is preferred", "Stopping is preferred", "Compulsory stop", "Do not stop"],
      answer: "Continuing is preferred",
      explanation: "ز (Waqf Mujawwaz) - continuing is better, though stopping is permitted",
    },
    {
      id: "wq10",
      word: "وقف ممنوع",
      transliteration: "Waqf Mamnoo",
      question: "Which waqf sign means you absolutely must NOT stop?",
      options: ["لا", "م", "ج", "ط"],
      answer: "لا",
      explanation: "لا (Waqf Mamnoo) is the sign that forbids stopping - continuing is obligatory",
    },
  ],
}

export function generateQuiz(topics, count) {
  let pool = []
  for (const topic of topics) {
    if (questions[topic]) pool = [...pool, ...questions[topic]]
  }
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1))
    ;[pool[i], pool[j]] = [pool[j], pool[i]]
  }
  const selected = pool.slice(0, Math.min(count, pool.length))
  return selected.map(q => ({
    ...q,
    options: [...q.options].sort(() => Math.random() - 0.5),
  }))
}

export const TOPICS = [
  { id: 'noon_sakinah', label: 'Noon Sakinah', arabic: 'النون الساكنة', desc: 'Ithaar, Idghaam, Iqlaab, Ikhfaa' },
  { id: 'qalqalah', label: 'Qalqalah', arabic: 'القلقلة', desc: 'Sughra, Wusta & Kubra' },
  { id: 'waqf', label: 'Waqf Signs', arabic: 'علامات الوقف', desc: 'Stop, continue & pause signs' },
]